import {StyleSheet} from 'react-native';
import {Colors, FontSizes, FontWeights, Shadows} from '../../theme/theme';
import {scale} from '../../utils/scaling';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContainer: {
    padding: scale(20),
  },
  headerContainer: {
    alignItems: 'center',
    paddingVertical: scale(24),
    paddingHorizontal: scale(20),
    marginBottom: scale(10),
  },
  iconContainer: {
    alignItems: 'center',
  },
  iconBackground: {
    width: scale(64),
    height: scale(64),
    borderRadius: 40,
    backgroundColor: '#e8f5e8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: FontSizes.large,
    fontWeight: FontWeights.semiBold,
    color: Colors.title,
    marginTop: scale(8),
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: FontSizes.small,
    color: Colors.gray,
    marginTop: scale(4),
    textAlign: 'center',
    fontStyle: 'italic',
  },
  section: {
    marginBottom: scale(20),
  },
  sectionTitle: {
    color: Colors.title,
    fontSize: FontSizes.small,
    marginBottom: scale(10),
    flexDirection: 'row',
    alignItems: 'center',
  },
  dropdownContainer: {
    position: 'relative',
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    borderRadius: scale(8),
    paddingHorizontal: scale(16),
    paddingVertical: scale(14),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  dropdownButtonContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dropdownButtonText: {
    fontSize: FontSizes.small,
    color: Colors.inputText,
    marginLeft: scale(10),
  },
  dropdownList: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: Colors.white,
    borderRadius: scale(8),
    marginTop: scale(4),
    borderWidth: 1,
    borderColor: Colors.border,
    zIndex: 1000,
    overflow: 'hidden',
    ...Shadows.medium,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: scale(12),
    paddingHorizontal: scale(16),
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  dropdownItemSelected: {
    backgroundColor: Colors.background,
  },
  dropdownItemText: {
    fontSize: FontSizes.small,
    color: Colors.inputText,
    marginLeft: scale(10),
  },
  dropdownItemTextSelected: {
    fontWeight: FontWeights.semiBold,
  },
  input: {
    padding: scale(16),
    borderWidth: 1,
    borderColor: Colors.border,
    height: 100,
    textAlignVertical: 'top',
    fontSize: FontSizes.small,
    borderRadius: scale(8),
  },
  imageSection: {
    alignItems: 'center',
  },
  imagePickerButton: {
    backgroundColor: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    backgroundColor: '#10b981',
    paddingVertical: scale(16),
    paddingHorizontal: scale(24),
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#10b981',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    width: '100%',
  },
  imagePickerText: {
    color: Colors.white,
    fontSize: scale(16),
    fontWeight: FontWeights.semiBold,
    marginTop: scale(8),
  },
  imagePickerSubText: {
    color: '#a7f3d0',
    fontSize: scale(12),
    marginTop: scale(2),
  },
  imagePreviewContainer: {
    marginTop: scale(16),
    paddingVertical: scale(8),
  },
  imageWrapper: {
    position: 'relative',
    marginRight: scale(12),
  },
  previewImage: {
    width: scale(100),
    height: scale(100),
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#d1fae5',
  },
  removeImageButton: {
    position: 'absolute',
    top: -scale(6),
    right: -scale(6),
    backgroundColor: '#ef4444',
    borderRadius: 12,
    width: scale(24),
    height: scale(24),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#ef4444',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
});
