import {StyleSheet} from 'react-native';
import {Colors, FontSizes, FontWeights, Shadows} from '../../theme/theme';
import {scale} from '../../utils/scaling';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContainer: {
    padding: scale(20),
    paddingBottom: scale(60),
  },
  headerContainer: {
    alignItems: 'center',
    paddingVertical: scale(24),
    paddingHorizontal: scale(20),
    marginBottom: scale(10),
  },
  iconContainer: {
    alignItems: 'center',
  },
  iconBackground: {
    width: scale(64),
    height: scale(64),
    borderRadius: 40,
    backgroundColor: '#e8f5e8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: FontSizes.large,
    fontWeight: FontWeights.semiBold,
    color: Colors.title,
    marginTop: scale(8),
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: FontSizes.small,
    color: Colors.gray,
    marginTop: scale(4),
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: scale(18),
  },
  section: {
    marginBottom: scale(20),
  },
  sectionTitle: {
    color: Colors.title,
    fontSize: FontSizes.small,
    marginBottom: scale(10),
    flexDirection: 'row',
    alignItems: 'center',
  },
  dropdownContainer: {
    position: 'relative',
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    borderRadius: scale(8),
    paddingHorizontal: scale(16),
    paddingVertical: scale(14),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  dropdownButtonContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dropdownButtonText: {
    fontSize: FontSizes.small,
    color: Colors.black,
    marginLeft: scale(10),
  },
  dropdownList: {
    position: 'absolute',
    top: scale(48),
    left: 0,
    right: 0,
    backgroundColor: Colors.white,
    borderRadius: scale(8),
    marginTop: scale(4),
    borderWidth: 1,
    borderColor: Colors.border,
    zIndex: 1000,
    overflow: 'hidden',
    ...Shadows.medium,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: scale(12),
    paddingHorizontal: scale(16),
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  dropdownItemSelected: {
    backgroundColor: Colors.primary + '20',
  },
  dropdownItemText: {
    fontSize: FontSizes.small,
    marginLeft: scale(10),
  },
  dropdownItemTextSelected: {
    color: Colors.primary,
    fontWeight: FontWeights.bold,
  },
  input: {
    lineHeight: scale(18),
    padding: scale(16),
    borderWidth: 1,
    borderColor: Colors.border,
    height: scale(120),
    textAlignVertical: 'top',
    fontSize: FontSizes.small,
    borderRadius: scale(8),
  },
  imageSection: {
    alignItems: 'center',
  },
  imagePickerButton: {
    paddingVertical: scale(20),
    paddingHorizontal: scale(24),
    width: '100%',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: Colors.border,
  },
  imagePickerText: {
    color: Colors.gray,
    marginTop: scale(2),
    fontSize: FontSizes.small,
    fontWeight: FontWeights.semiBold,
  },
  imagePreviewContainer: {
    marginTop: scale(16),
    paddingVertical: scale(8),
  },
  imageWrapper: {
    position: 'relative',
    marginRight: scale(12),
  },
  previewImage: {
    width: scale(100),
    height: scale(100),
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  removeImageButton: {
    position: 'absolute',
    top: -scale(6),
    right: -scale(6),
    backgroundColor: Colors.red_2,
    borderRadius: 999,
    width: scale(24),
    height: scale(24),
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonActions: {
    flexDirection: 'row',
    gap: scale(10),
    paddingHorizontal: scale(20),
    paddingVertical: scale(16),
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.border_2,
  },
  cancelButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    backgroundColor: '#F5F5F5',
  },
  cancelButtonText: {
    color: '#666',
  },
  inputError: {
    borderColor: Colors.red,
  },
  errorText: {
    color: Colors.red,
    marginTop: scale(4),
    fontSize: FontSizes.small,
  },
});
